# Generated by Django 5.2.4 on 2025-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
