# Generated by Django 5.2.4 on 2025-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_lesson_deleted_at_lesson_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
