# Generated by Django 5.2.4 on 2025-07-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_remove_examquestion_course_exam_examquestion_exam_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together=set(),
        ),
    ]
