# Generated by Django 5.2.4 on 2025-07-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
    ]
